branches:
  only:
    - master
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autopoint expat libnuma-dev libcap-dev
script: autoreconf -fi && ./configure && make -j4 && make check
notifications:
  email:
    recipients:
      - jamesodhunt@ubuntu.com
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "lWtQPuzdQgdrH4jhpdyTfnm9BHbTkyi7NfEtHf3nFCOwzx8ZWdlRhgkT3hd8fPxhhB4JfzrGpBhF4tBeOEPDTd1zlgMtyg0xtlyAzCUh4HO2E8V2bvXnTYYcHAFDDPrQs++4UW0oURviUog3eBJAunxh5f7NGrtc7gsyoZ8dANN4oLTTbmUloYL9UZ69EC0JzeXCTWK9AkCpIaU9lYGRdzYM0piqtokBoA3a2F4jn/yqD1SWn4JFn0gxbHylBENj3wz7P2LnLLu7zRCC0GG82kRv9ZBdkeOUgiYe9nPsAqWc6HVtpt/uP8PSJSaO9VlLu48c3WfkxV7ieahIn/N8mg53FXGchlMv5OEE/fGoVKyWbDemNZ2hEhca1N63rI5TositJw8vl/B10R19BSfBrgwdk3uHiP+rcHy1pbs0xOHnsEF6JjJTig3qc+HJej70+ud/9Bm4Ag6Z7OyttcdVQMQ1KErNSbsoYSvmFPI+UKAQrZZ+ek8SINPH8nKKuTaIhMPB72j10zokg4FVng7Nk67ChUKn2YY801qe9APsLrKcw3AhtubKPSZp6c9ZWByxraP///itpl/AvsYso4aEWAGuJKHF1hu6ao4b9z72PkqR9xb1mLjUGp1nLQopLvoRNTOpkAwXH+sZdoKLr97bgx+gHW8s2H8u5Dol+s4kCJQ="
addons:
  coverity_scan:
    project:
      name: "jamesodhunt/procenv"
      description: "Build submitted via Travis CI"
    notification_email: jamesodhunt@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
